### ISSUE TITLE
n字符及后面字母都无法显示

### ISSUE THREAD

**Issue by yty666zsy** [Royikiss/Smarthome#1]
![image](https://github.com/user-attachments/assets/47f2765f-3c1d-492b-819c-d6c2da8eb92a)
![image](https://github.com/user-attachments/assets/932013cc-e9e3-4cff-a42f-69d723c85a87)

**Comment by Royikiss** [comment]
已修复https://github.com/Royikiss/Smarthome/commit/93923c1476e73a477902a53196d79d9f63088f2b
